title: GraalPy
description: GraalPy is a Python 3.10 compliant runtime on top of GraalVM. GraalPy offers high-performance execution, modern language features, and easy interoperability with Java. 
url: https://graalpy.github.io
baseurl: #
# Build settings
markdown: kramdown
theme: minima

tables_of_contents:
  - 
    subgroups:
      - main_link: docs/graalpy-embedded/reference/Interoperability.md,
      - main_link: docs/graalpy-embedded/reference/Java_Interoperability.md,
      - main_link: docs/graalpy-embedded/reference/Jython.md,
      - main_link: docs/graalpy-embedded/reference/Native_Images.md,
      - main_link: docs/graalpy-embedded/reference/OS_Interfaces.md,
      - main_link: docs/graalpy-embedded/reference/Parser_Details.md,
      - main_link: docs/graalpy-embedded/reference/Standalone_Embedded_Applications.md

kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-toc

toc:
    min_level: 1
    max_level: 3

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - script
  - vendor

defaults:
  sitemap: false