title: GraalPy
description: GraalPy is a Python 3.10 compliant runtime on top of GraalVM. GraalPy offers high-performance execution, modern language features, and easy interoperability with Java. 
url: https://graalpy.github.io
baseurl: ""

header_pages:
  - docs/Getting_Started.md
  - docs/guides/Guides.md
  - docs/examples/Examples.md
  - docs/reference/Reference.md

footer_pages:
  - docs/contributor/Contributing.md
  - docs/License.md

# Build settings
markdown: kramdown
theme: minima

kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-toc

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - script
  - vendor

defaults:
  sitemap: false